version: "3.8"
services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
